openapi: 3.0.1
info:
  title: Expense Tracker Api
  description: Expense tracking api
  version: 2.0.0
servers:
  - url: /api/v2
tags:
  - name: Sheets
    description: Sheet management endpoints
  - name: Specification
    description: The swagger API specification
paths:
  /sheets/{docId}:
    post:
      summary: Create a sheet
      tags:
        - Sheets
      description: This operation needs correct Document Id in the url
      parameters:
        - name: docId
          in: path
          required: true
          description: Document id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                resSheetName:
                  type: string
                  example: Sheet1
              required:
                - resSheetName
      responses:
        201:
          description: Sheet created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseType'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    delete:
      summary: Delete a sheet
      tags:
        - Sheets
      description: This operation needs correct Document Id in the url
      parameters:
        - name: docId
          in: path
          required: true
          description: Document id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                resSheetName:
                  type: string
                  example: Sheet1
              required:
                - resSheetName
      responses:
        200:
          description: Sheet deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseType'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /sheets/{docId}/row:
    post:
      summary: Create an entry
      tags:
        - Rows
      description: This operation needs correct Doc Id in the url
      parameters:
        - name: docId
          in: path
          required: true
          description: Document id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                title:
                  type: string
                  example: test
                expense:
                  type: string
                  example: '40'
                file:
                  type: string
                  example: 'data:image/jpeg;base64'
                resSheetName:
                  type: string
                  example: Sheet1
                ShouldAddToNextMonth:
                  type: string
                  example: '0'
              required:
                - title
                - expense
      responses:
        201:
          description: Entry created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedResponseType'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    patch:
      summary: Update an entry
      tags:
        - Rows
      description: This operation needs correct Document Id in the url
      parameters:
        - name: docId
          in: path
          required: true
          description: Document id
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                id:
                  type: integer
                  example: 0
                title:
                  type: string
                  example: test
                expense:
                  type: string
                  example: '-40'
                resSheetName:
                  type: string
                  example: Sheet1
                ShouldAddToNextMonth:
                  type: string
                  example: '1'
              required:
                - id
      responses:
        200:
          description: Entry updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseType'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    delete:
      summary: Delete an entry
      tags:
        - Rows
      description: This operation needs correct Document Id in the url
      parameters:
        - name: docId
          in: path
          required: true
          description: Document id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                id:
                  type: integer
                  example: 0
                resSheetName:
                  type: string
                  example: Sheet1
              required:
                - id
      responses:
        200:
          description: Entry deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseType'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
components:
  schemas:
    InternalServerError:
      title: Server Error
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
      example:
        errors: [{ message: 'Something went wrong.' }]
    ResponseType:
      title: Response Type
      type: object
      properties:
        result:
          type: string
        errors:
          type: array
          items:
            type: string
      example:
        - { result: 'Ok', errors: [] }
        - { result: '', errors: ['Something went wrong.'] }
    CreatedResponseType:
      title: Created Response Type
      type: object
      properties:
        result:
          type: string
        payload:
          type: object
          properties:
            Title:
              type: string
            Expense:
              type: string
            File:
              type: string
            CreatedAt:
              type: string
            ShouldAddToNextMonth:
              type: string
        errors:
          type: array
          items:
            type: string
      example:
        - {
            result: 'Ok',
            payload:
              {
                Title: 'test',
                expense: '40',
                file: 'kt.imagekit.io/expense-tracker/hello.jpg',
                ShouldAddToNextMonth: '0',
              },
            errors: [],
          }
        - { result: '', errors: ['Something went wrong.'] }
